### ISSUE TITLE
 The metadata storage is not up to date when using MariaDBPlatform platform

### ISSUE THREAD

**Issue by delacry** [doctrine/migrations#1281]
Hi, when I use my custom platform that extends `Doctrine\DBAL\Platforms\MariaDBPlatform` with UUID support for MariaDB 10.7+, or simply that specific `MariaDBPlatform`, I get an error when I try to generate migrations with diff.
```
The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue. 
```

Error is thrown at TableMetadataStorage::checkInitialization() because `$this->needsUpdate($expectedTable)` is not null but this - https://code.rixafy.pro/drp3MB5j (var dump).

https://github.com/doctrine/migrations/blob/3.5.x/lib/Doctrine/Migrations/Metadata/Storage/TableMetadataStorage.php#L237

## Temporary solution

Now I noticed that $this->platform in that class is `\Doctrine\DBAL\Platforms\MariaDb1027Platform` (it's deprecated) and not `Doctrine\DBAL\Platforms\MariaDBPlatform`, so when I use this, or when I use my own platform with UUID support like this `MariaDb1070Platform extends MariaDb1027Platform` it's working.

I have also seen some advices https://stackoverflow.com/questions/62412312/symfony-makemigration-the-metadata-storage-is-not-up-to-date-please-run-the but that didn't help, I'm using MariaDB 10.10.1.

**Comment by dmamchyts** [comment]
```
  - Downgrading doctrine/dbal (3.5.0 => 3.4.6)
```

**Comment by manuelkiessling** [comment]
Same here. My Symfony project requires `doctrine/doctrine-migrations-bundle:^3.2`, which in turn requires `doctrine/migrations:^3.2`, which in turn requires `doctrine/dbal:^3.3`.

When upgrading the project with `composer update`, then `doctrine/dbal` is upgraded from `3.4.5` to `3.5.0`.

Afterwards, my Symfony `6.1` project, which uses PHP `8.1.11` and talks to a MariaDB `10.5.13` database, stops working because it always runs into the `The metadata storage is not up to date` issue, returned from [`lib/Doctrine/Migrations/Exception/MetadataStorageError.php:13`](https://github.com/doctrine/migrations/blob/3.5.x/lib/Doctrine/Migrations/Exception/MetadataStorageError.php#L13).

I've ensured that my `DATABASE_URL` string contains `serverVersion=mariadb-10.5.13`, and have repeatedly run the `doctrine:migrations:sync-metadata-storage` command, to no avail.

Explicitly defining the `storage.table_storage` configuration in file `config/packages/doctrine_migrations.yaml`, instead of using the defaults, also doesn't help.

I have already isolated `doctrine/dbal 3.4.5 => 3.5.0` as the problematic upgrade, by updating only this dependency in isolation, with the same result.

**Comment by greg0ire** [comment]
See https://github.com/doctrine/dbal/pull/5779

**Comment by derrabus** [comment]
DBAL 3.5.1 should fix the issue.

**Comment by delacry** [comment]
Well, didn't help
```
Upgrading doctrine/dbal (3.4.5 => 3.5.1): Checking out f38ee8aaca from cache
```

```
website@Magnus ~/websites/primary/dev # bin/console migrations:diff

In MetadataStorageError.php line 13:
                                                                                                           
  The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue.  
```
and the issue still remains when I use `\Doctrine\DBAL\Platforms\MariaDBPlatform` with MariaDB 10.10.1, so I'm using deprecated platform `Doctrine\DBAL\Platforms\MariaDb1027Platform` which I extend with UUID support for now.

**Comment by delacry** [comment]
And I have also tried database url instead of config parameters (with version specified), but didn't help either.

![image](https://user-images.githubusercontent.com/45132928/197534247-30e98777-e088-4704-96ec-3d936082fca8.png)

**Comment by greg0ire** [comment]
Sorry, I thought this was the same issue because of @manuelkiessling, but you reported it earlier than when we released 3.5.0

**Comment by delacry** [comment]
Np, I noticed that I had 3.4.5 when I was updating, it's some different problem with that platform, because now the default platform is that deprecated one when I don't set any platform.

**Comment by delacry** [comment]
And I forgot to mention, I'm using Nette Framework and here is the integration, https://github.com/contributte/doctrine-dbal/blob/master/src/DI/DbalExtension.php but I don't think this have something do with it.

**Comment by derrabus** [comment]
Can you provide a reproducer for this issue?

**Comment by marienpflaum** [comment]
This is not only a problem on MariaDB. We are using Mysql 8.0 and are experiencing the same problems. As far as we can telll something goes wrong when the diff is calculated. It could be related (in our case) to the collation of the version column of the migration table. In the diff those values do not match the expected table.

**Comment by Fabrizio1985** [comment]
I have the same problem with sqlite with doctrine/dbal 3.5.2.

The problem is in class SqliteSchemaManager  on row 327

`
if ($type instanceof StringType || $type instanceof TextType) {
     $column->setPlatformOption(
            'collation',
            $this->parseColumnCollationFromSQL($columnName, $createSql) ?? 'BINARY',
     );
}
`

This code allways add property collation = BINARY and when doing diff return error.

If i comment this setPlatformOption i have no problem.

**Comment by stof** [comment]
@Fabrizio1985 for sqlite on dbal 3.5.2, this should be fixed by https://github.com/doctrine/dbal/pull/5861 which has just been merged into the 3.5.x branch of DBAL (a 3.5.3 release should come soon)

**Comment by greg0ire** [comment]
I released 3.5.3 this morning

**Comment by Fabrizio1985** [comment]
> I released 3.5.3 this morning

Wonderfull work!! Thanks

**Comment by greg0ire** [comment]
I'm going to close, let me know if I should reopen, anybody.
