### ISSUE TITLE
Strange behavior on migrate: get an error "Unknown database type"

### ISSUE THREAD

**Issue by aaleksu** [doctrine/migrations#525]
Guys, I have pretty big project with a lot of tables.
I create a new migration and try to execute it. When executing I get and error:
"Unknown database type json requested, Doctrine\DBAL\Platforms\PostgreSqlPlatform may not support it".

1. It's not clear which table caused the problem, why, and what to do with that. Why don't you put the column name and the table name into exception message?
2. There is no json field in the table I am trying to alt.
3. The type of column I add in new migration is not json. Why this exception is thrown now? I does not relate to my new migration. Why don't you check only those tables which migration is related to? Why you check all the tables?

Maybe the better solution is to warn the user that there is some shit in his data and to give him to choose what to do?

**Comment by chrisguitarguy** [comment]
Could you post your migration that caused the error? Are you using migrations with the ORM?

**Comment by aaleksu** [comment]
> Could you post your migration that caused the error?
Sure. It's pretty stupid: "alter table <table> rename <old_column> to <new_column>"

> Are you using migrations with the ORM?
Yes.

The problem is that my migration and the error I got are absolutely disconnected. They have nothing to do with each other. And the exception message is unhelpful: I don't even know where to look.

**Comment by chrisguitarguy** [comment]
ORM version? DBAL Version? Migrations version? What was the class of the exception being thrown (the console commands should output that for you).

The error message sounds like it could be from the [DBAL type system](https://github.com/doctrine/dbal/blob/3632e03cb11fd5d6e382854514bf5fc0e0c5870e/lib/Doctrine/DBAL/Types/Type.php#L175-L177).

You should be able to crank up the verbosity on the console and see where things came from:

```
./bin/console doctrine:migrations:migrate -vvv # symfony

./vendor/bin/migrations migrations:migrate -vvv # migrations CLI
```

**Comment by aaleksu** [comment]
> ORM version?

2.4.8

> DBAL Version?

2.4.5

> Migrations version?

2.1

> The error message sounds like it could be from the DBAL type system.

Yes, it comes from the DBAL.

Here is output of migrate command:

Migration 20170504183108 failed during Pre-Checks. Error Unknown database type json requested, Doctrine\DBAL\Platforms\PostgreSqlPlatform may not support it.

                                                                                                        
  [Doctrine\DBAL\DBALException]                                                                         
  Unknown database type json requested, Doctrine\DBAL\Platforms\PostgreSqlPlatform may not support it.  
                                                                                                        

Exception trace:
 () at /var/www/superkassa/frontend/Symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php:327
 Doctrine\DBAL\Platforms\AbstractPlatform->getDoctrineTypeMapping() at /var/www/superkassa/frontend/Symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/PostgreSqlSchemaManager.php:284
 Doctrine\DBAL\Schema\PostgreSqlSchemaManager->_getPortableTableColumnDefinition() at /var/www/superkassa/frontend/Symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:776
 Doctrine\DBAL\Schema\AbstractSchemaManager->_getPortableTableColumnList() at /var/www/superkassa/frontend/Symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:162
 Doctrine\DBAL\Schema\AbstractSchemaManager->listTableColumns() at /var/www/superkassa/frontend/Symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:267
 Doctrine\DBAL\Schema\AbstractSchemaManager->listTableDetails() at /var/www/superkassa/frontend/Symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:254
 Doctrine\DBAL\Schema\AbstractSchemaManager->listTables() at /var/www/superkassa/frontend/Symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:986
 Doctrine\DBAL\Schema\AbstractSchemaManager->createSchema() at /var/www/superkassa/frontend/Symfony/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Version.php:252
 Doctrine\DBAL\Migrations\Version->execute() at /var/www/superkassa/frontend/Symfony/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Migration.php:175
 Doctrine\DBAL\Migrations\Migration->migrate() at /var/www/superkassa/frontend/Symfony/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Tools/Console/Command/MigrateCommand.php:143
 Doctrine\DBAL\Migrations\Tools\Console\Command\MigrateCommand->execute() at /var/www/superkassa/frontend/Symfony/vendor/doctrine/doctrine-migrations-bundle/Command/MigrationsMigrateDoctrineCommand.php:55
 Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute() at /var/www/superkassa/frontend/Symfony/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:246
 Symfony\Component\Console\Command\Command->run() at /var/www/superkassa/frontend/Symfony/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:863
 Symfony\Component\Console\Application->doRunCommand() at /var/www/superkassa/frontend/Symfony/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:185
 Symfony\Component\Console\Application->doRun() at /var/www/superkassa/frontend/Symfony/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:90
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/superkassa/frontend/Symfony/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:115
 Symfony\Component\Console\Application->run() at /var/www/superkassa/frontend/Symfony/app/console:22

**Comment by stof** [comment]
Can you show your Migration class ?

**Comment by chrisguitarguy** [comment]
> 2.4.5

Could be that the `JSON` type isn't present in [DBAL 2.4.X](https://github.com/doctrine/dbal/blob/2.4/lib/Doctrine/DBAL/Types/Type.php#L38), only `JSON_ARRAY` is there.

**Comment by stof** [comment]
Btw, if you want to report bugs, you should make sure to use a maintained version of Doctrine. ORM 2.4 and DBAL 2.4 are both very old.

**Comment by aaleksu** [comment]
> Could be that the JSON type isn't present

It's not the point of my issue.
What I am saying is that there is no need to check working database schema. It's only necessary to check current migration which is about to be executed.
If database, as it is (with all its unsupported types), works, why not to allow to execute new migration?

> if you want to report bugs

I am not sure it's a bug.
If ORM and DBAL didn't change in their besics and the call stack is mostly the same then - I am pretty sure - this behavior is present in current versions of ORM and DBAL. But I will check it.

**Comment by stof** [comment]
@aaleksu you haven't answered my previous request though: https://github.com/doctrine/migrations/issues/525#issuecomment-299226782

**Comment by chrisguitarguy** [comment]
> What I am saying is that there is no need to check working database schema.

Migrations doesn't do that unless you interact with the schema object in your migrations. See #407 (present in migrations 1.2).

**Comment by aaleksu** [comment]
> you haven't answered my previous request

Honestly, I don't see how it can help, but anyway here it is:

<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

class Version20170504183108 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->addSql('select 1'); // actually here might be absolutely any sql
    }

    public function down(Schema $schema)
    {
    }
}

I really tried this query ('select 1') and it caused the error.

**Comment by aaleksu** [comment]
> Migrations doesn't do that unless you interact with the schema object in your migrations

Well, yes, but schema is being injected into up() and down() methods by default.
Are there any other methods which might be called to execute migration or just up and down?
I don't see any in Doctrine\DBAL\Migrations\AbstractMigration.

**Comment by chrisguitarguy** [comment]
> Well, yes, but schema is being injected into up() and down() methods by default.

Those are [proxy objects](https://github.com/Ocramius/ProxyManager) that only initialize themselves when they are interacted with for the first time.

So they are passed to up/down, but they are not reading your database schema until something like a method call or property access is done on them.

**Comment by stof** [comment]
Can you tell us which version of doctrine/migrations you are actually using ? Your previous comment says 2.1 but this is impossible. The latest version is 1.5.0

**Comment by aaleksu** [comment]
>  which version of doctrine/migrations you are actually using ? Your previous comment says 2.1 but this is impossible. The latest version is 1.5.0

Oh, sorry. I looked version number in doctrine/migrations/LICENSE file.
My composer.locak says it's 1.1.

**Comment by stof** [comment]
Well, version 1.1 needs to be able to introspect the DB, as it does not use proxy objects yet (btw, this introspection is quite slow, and happens for each migration, so I strong suggest you to upgrade. I achieved a 94% speed improvement on my project when migrating, and it would be even bigger today as I have more migrations)

**Comment by aaleksu** [comment]
> So they are passed to up/down, but they are not reading your database schema until something like a method call or property access is done on them

Ok.
I followed the chain of calls and it starts from AbstractSchemaManager#createSchema. then listTables is being called and so on.

**Comment by aaleksu** [comment]
> I strong suggest you to upgrade. I achieved a 94% speed improvement

Speed is not the point. I don't care about speed. I it let me execute my migration - even slow - it would be OK. But it doesn't and doesn't say anything helpful like table name or possible ways to fix - and that's the point.

**Comment by stof** [comment]
Where does your existing DB comes from ? What is created by Doctrine or another tool ?
And does it contain any JSON field ?

**Comment by stof** [comment]
OK, I think I found it: support for JSON fields of Postgresql 9.2+ in the schema introspection was added in DBAL 2.5.
So your issue is clear: you are using a version of DBAL which does not contain any of the features added in the last 3 years, and which is not maintained anymore since 2 years. And your DB uses a feature for which support was added during this time.

So I will stop being involved in this discussion, as long as a maintained version of DBAL is not used. It is just wasting my time.

**Comment by mikeSimonson** [comment]
Closing as this is fixed in newer version of doctrine migration that was released more than a year ago (1.3).

**Comment by aaleksu** [comment]
I installed doctrine/migrations version 1.5.
Seems it doesn't check all the tables at each migration now.

But the exception message is still not helpful: https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php#L429.
It names only db type and called class name, but not table name (what is crucially important).

**Comment by chrisguitarguy** [comment]
> But the exception message is still not helpful: 

Agreed, but that's an issue for the DBAL repo, not migrations.

**Comment by aaleksu** [comment]
Ah, yes, you're right.
